// variable naming notes:
// clock domain is the prefix. "o" or "vout" for video output domain, 
// "vin" or "i" for video input domain, "mem" or "m" for DDR3 domain

/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off WIDTHTRUNC */


/*  TODO: 

    implement frame slot

    Check which pixel counts we actually need. Pixels? Words? Or maybe just change
    to bytes and address only on bytes? Would need a few other redos (addressing, 
    MEM_INCREMENT, all that jazz)
*/

module fb_mem_control #(
    parameter int ADDR_WIDTH = 32,
    parameter int MEMORY_WIDTH = 128,
    parameter int PIXEL_SIZE = 24,
    parameter int BURST_SIZE = 16, // Number of pixels per burst
    parameter int MAX_LINE_WIDTH = 9, // Bits needed to describe the number of memory words per line
    parameter int MEM_INCREMENT = 1 // in counts of bursts (128bit/16byte)
)(
    input  logic                    rstn_i,

    // DDR3 memory interface
    input  logic                    mem_clk_i,
    input  logic                    mem_busy_i,
    output logic                    mem_wr_en_o,
    output logic                    mem_rd_en_o,
    output logic [ADDR_WIDTH-1:0]   mem_addr_o,
    output logic [MEMORY_WIDTH-1:0] mem_wr_data_o,
    input  logic [MEMORY_WIDTH-1:0] mem_rd_data_i,
    input  logic                    mem_rd_data_valid_i,

    // Video input interface
    input  logic                    vin_clk_i,
    input  logic [9:0]              vin_width_i,  // input image width (max: 1024)
    input  logic [8:0]              vin_height_i, // input image height (max: 512)
    input  logic                    vin_buf_wr_en_i, // Pixel ready to go to DDR3 FIFO
    input  logic [PIXEL_SIZE-1:0]   vin_buf_data_i, 
    input  logic [9:0]              vin_buf_start_pixel_i, // Pixel value at the start of most recent burst
    input  logic [9:0]              vin_buf_start_word_i,
    input  logic [8:0]              vin_buf_line_i, // Line for that same burst
    input  logic                    vin_buf_data_ready_i, // Burst has been filled 
    input  logic                    vin_buf_data_flush_i, // FIFO flush command
    input  logic [9:0]              vin_line_length_i, // Length of a line counted in memory words
    input  logic [1:0]              vin_frame_slot_i, // triple buffering uses 3 slots. Increment on Vsync

    // Video output interface
    input  logic                    vout_clk_i,
    input  logic                    vout_buf_data_req_i,
    input  logic [8:0]              vout_buf_rd_line_i,
    input  logic [9:0]              vout_buf_rd_pixel_i,
    input  logic [9:0]              vout_buf_rd_word_i, // Memory data word number for start of most recent burst
    output logic                    vout_buf_rd_complete_o, // asserted when burst read is complete
    input  logic                    vout_buf_rd_en_i,
    output logic [PIXEL_SIZE-1:0]   vout_buf_rd_data_o
);

// tabs = 4 spaces

/* 
FUNCTIONALITY OF THIS MODULE:

Video input side:
Receives FIFO pushes from video input one pixel at time
Assembles pixels 24bit (8,8,8 RGB) into 128 bit DDR words
Receives buffer write signals including video row, column, and frame number/save slot

Video output side:
Receives buffer read signals with row, column (and frame slot? or is that generated internally?)
Pops FIFO one 128-bit read at a time, disassembles into individual 24-bit pixels

Memory side:
Writes to memory when video input asserts buffer write, reads when video output
asserts buffer read.
Writes:
- wr_en asserted with addr and data, writes are accepted when busy is low
Reads:
- rd_en asserted with just the address. Read command is accepted when
  busy is low. Read finished when data returned with rd_data_valid high
Addressing is done by frame slot, line, and pixel. Frame slot is generated by the write controller,
and is initially zero (meaning no valid frame has been saved yet). Otherwise, it is the most recent
COMPLETED frame. So when writing, we write to the slot AFTER vin_frame_slot_i, but when reading we
read from the named slot. Also it's 1-indexed so that zero is an invalid slot. The read controller
should output blank frames while vin_frame_slot_i is zero.
Examples:
- video input:
-- frame slot -- write address shift --
--     0      --        0            --
--     1      --        1            --
--     2      --        2            --
--     3      --        0            --
- video output:
-- frame slot -- read  address shift --
--     0      --        2            --
--     1      --        0            --
--     2      --        1            --
--     3      --        2            --
*/

localparam int MEM_BYTES = MEMORY_WIDTH/8; // 128-bit => 16 bytes
localparam int PIX_BYTES = PIXEL_SIZE/8; // 24-bit => 3 bytes
localparam int MEM_BYTES_WIDTH = $clog2(MEM_BYTES); // 16 bytes => 4 bits

localparam int MEM_BURST_SIZE = BURST_SIZE * PIXEL_SIZE / MEMORY_WIDTH;
localparam int MEM_BURST_WIDTH = $clog2(MEM_BURST_SIZE);

logic [MEMORY_WIDTH-1:0] i_fifo_wr_data;
logic [(PIX_BYTES-1)*8-1:0] i_fifo_wr_data_r; // overlap data, written if a pixel is partially written at the end of a memory word
logic [MEM_BYTES_WIDTH-1:0] i_align; // byte alignment pointer of write data
logic i_overflow; // overflow in previous write
logic i_fifo_wr; // write to the MEMORY_WIDTH sized FIFO
integer i;

always_ff @(posedge vin_clk_i or negedge rstn_i) begin
    if(!rstn_i) begin
        i_fifo_wr_data <= 0;
        i_fifo_wr <= 0;
        i_align <= 0;
        i_overflow <= 0;
    end else begin
        i_fifo_wr <= 0;

        if (vin_buf_wr_en_i) begin
            // if (i_align <= (MEM_BYTES - PIX_BYTES)) begin
            //     i_fifo_wr_data[(i_align*8) +: PIXEL_SIZE] <= vin_buf_data_i;
            // end else begin
                for (i = 0; i < PIX_BYTES; i = i + 1) begin
                    if ((int'(i_align) + i) < MEM_BYTES) begin
                        i_fifo_wr_data[((i_align+i)*8) +: 8] <= vin_buf_data_i[(8*i) +: 8];
                    end else begin
                        // write wraparound bytes to the temp register
                        i_fifo_wr_data_r[((int'(i_align) + i - MEM_BYTES)*8) +: 8] <= vin_buf_data_i[(8*i) +: 8];
                    end
                end
            // end
            i_align <= i_align + MEM_BYTES_WIDTH'(PIX_BYTES);
            if (int'(i_align) > (MEM_BYTES - PIX_BYTES))
                i_overflow <= 1;
            if (int'(i_align) >= (MEM_BYTES - PIX_BYTES))
                i_fifo_wr <= 1;
        end

        if (vin_buf_data_flush_i) begin
            // write whatever is already in the buffer
            if (i_align != 0) begin
                i_fifo_wr <= 1;
                i_align <= 0;
            end
        end

        if ( i_overflow == 1) begin
            i_overflow <= 0;
            for (i = 0; i < PIX_BYTES-1; i = i + 1) begin
                if(i_align > i) begin
                    i_fifo_wr_data[(i*8) +: 8] <= i_fifo_wr_data_r[(i*8) +: 8];
                end
            end
        end
    end
end


logic o_fifo_pop; // command to pop the MEMORY_WIDTH sized FIFO
logic [MEMORY_WIDTH-1:0] o_fifo_rd_data;
logic [MEM_BYTES_WIDTH-1:0] o_align; // byte alignment pointer of read data
logic [MEM_BYTES_WIDTH-1:0] o_next_align; // useful in overflow calculations
logic [(PIX_BYTES-1)*8-1:0] o_fifo_rd_data_r; // overlap data, written if a pixel is partially read at the end of a memory word
logic o_fifo_flush; // asserted any time a read request comes in with pixel=0 (first of the line)
integer o;

assign o_next_align = o_align + MEM_BYTES_WIDTH'(PIX_BYTES);

// determine if we need to pop the fifo
// should be done in combinatorial logic, as the data needs
// to be ready by the next cycle
always_comb begin
    o_fifo_pop = 0;
    if (vout_buf_rd_en_i) begin

        // must pop if the next request will have to use new FIFO data
        // that would be if the current alignment pointer is between PIX_BYTES 
        // and 2*PIX_BYTES from the end of the FIFO word

        // if we're closer than PIX_BYTES, we should have already popped
        if ((int'(o_next_align) > (MEM_BYTES - PIX_BYTES)) || (o_next_align == 0)) begin
            o_fifo_pop = 1;
        end
    end
end

always_ff @(posedge vout_clk_i or negedge rstn_i) begin
    if(!rstn_i) begin
        o_align <= 0;
        o_fifo_flush <= 0;
    end else begin

        if (vout_buf_data_req_i && (vout_buf_rd_word_i == 0)) begin
            o_fifo_flush <= 1;
            o_align <= 0;
        end else begin
            // TODO: maybe hold it for a few cycles?
            o_fifo_flush <= 0;
        end

        if (vout_buf_rd_en_i) begin
            // Special care for the cases when we are reading close to the end of the memory word (MEMORY_WIDTH size)
            // Near the end, we have to figure out when to trigger the next read. But sometimes a pixel
            // will overlap two different memory words. So...
            // - Save the last few bytes of the memory word to a small buffer that is at sized at least PIXEL_WIDTH minus
            //   one byte. Choose correct bytes to save based on current location of the alignment pointer
            // - On the following read, choose some bytes from the just-read memory word out of the FIFO, and some
            //   from the previously saved bytes from the last word.

            for (o = 0; o < PIX_BYTES-1; o = o + 1) begin
                // overflow bytes: save the end of the read data so the next FIFO pop can be appended to it
                if ((int'(o_next_align) ) > (MEM_BYTES - PIX_BYTES)) begin
                    if ((int'(o_next_align) + o) < MEM_BYTES) begin
                        o_fifo_rd_data_r[(8*o) +: 8] <= o_fifo_rd_data[(int'(o_next_align) + o)*8 +: 8];
                    end
                end
            end
            
            if (int'(o_align) > (MEM_BYTES - PIX_BYTES)) begin
                // append old saved bytes to this read
                for (o = 0; o < PIX_BYTES; o = o + 1) begin
                    if (int'(o_align) + o >= MEM_BYTES) begin
                        vout_buf_rd_data_o[(8*o) +: 8] <= o_fifo_rd_data[((int'(o_align)+o-MEM_BYTES)*8) +: 8];
                    end else begin
                        vout_buf_rd_data_o[(8*o) +: 8] <= o_fifo_rd_data_r[(8*o) +: 8];
                    end
                end
            end else begin
                // standard move - just move FIFO data to read data
                for(o = 0; o < PIX_BYTES; o = o + 1) begin
                    vout_buf_rd_data_o[(8*o) +: 8] <= o_fifo_rd_data[((int'(o_align)+o)*8) +: 8];
                end
            end
            o_align <= o_next_align;
        end
    end
end

logic m_fifo_pop;
logic [5:0] m_input_fifo_count;

cdc_fifo #(
    .RD_D_SIZE(MEMORY_WIDTH),
    .WR_D_SIZE(MEMORY_WIDTH),
    .RD_DEPTH(32),
    .WR_DEPTH(32)
) input_mem_fifo
(
    .Data(i_fifo_wr_data),
    .WrClk(vin_clk_i),
    .RdClk(mem_clk_i),
    .WrEn(i_fifo_wr),
    .RdEn(m_fifo_pop),
    .Reset(!rstn_i),
    .AlmostEmptySetTh(3),
    .AlmostEmptyClrTh(5),
    .AlmostFullSetTh(29),
    .AlmostFullClrTh(27),
    .Q(mem_wr_data_o),
    .Wnum(),
    .Rnum(m_input_fifo_count),
    .Almost_Empty(),
    .Almost_Full(),
    .Empty(),
    .Full()
);

cdc_fifo #(
    .RD_D_SIZE(MEMORY_WIDTH),
    .WR_D_SIZE(MEMORY_WIDTH),
    .RD_DEPTH(32),
    .WR_DEPTH(32)
) output_mem_fifo
(
    .Data(mem_rd_data_i),
    .WrClk(mem_clk_i),
    .RdClk(vout_clk_i),
    .WrEn(mem_rd_data_valid_i),
    .RdEn(o_fifo_pop),
    .Reset((!rstn_i) || (o_fifo_flush)),
    .AlmostEmptySetTh(3),
    .AlmostEmptyClrTh(5),
    .AlmostFullSetTh(29),
    .AlmostFullClrTh(27),
    .Q(o_fifo_rd_data),
    .Wnum(),
    .Rnum(),
    .Almost_Empty(),
    .Almost_Full(),
    .Empty(),
    .Full()
);


// *********** Memory interface *************
logic [$clog2(MAX_LINE_WIDTH):0] i_addr_shift;
assign i_addr_shift = calc_line_width(vin_line_length_i);
// Memory state machine
// Can only do one thing at a time (read or write)
// Read / write commands come from read_control and write_control
// modules. Address is generated by line, pixel, and frame input


logic [ADDR_WIDTH-1:0] i_wr_addr;
logic [ADDR_WIDTH-1:0] o_rd_addr;
always_comb begin
    i_wr_addr = vin_buf_start_word_i;
    i_wr_addr[i_addr_shift +: 9] = vin_buf_line_i;
    if (vin_frame_slot_i != 2'd3) 
        i_wr_addr[(i_addr_shift+9) +: 2] = vin_frame_slot_i;
    else
        i_wr_addr[(i_addr_shift+9) +: 2] = 2'b00;
end

always_comb begin 
    o_rd_addr = vout_buf_rd_word_i;
    o_rd_addr[i_addr_shift +: 9] = vout_buf_rd_line_i;
    if (vin_frame_slot_i != 2'd0)
        o_rd_addr[(i_addr_shift+9) +: 2] = (vin_frame_slot_i - 2'd1);
    else
        o_rd_addr[(i_addr_shift+9) +: 2] = 2'd2;
end

typedef enum logic[1:0] { 
    IDLE,
    READ,
    WRITE
} mem_state_t;

mem_state_t mem_state;

localparam int FLUSH_TIMER_LEN = 4; // cycles after CDC'd flush req is acted upon

logic [MEM_BURST_WIDTH:0] m_read_req_count;
logic [MEM_BURST_WIDTH:0] m_write_req_count;
logic m_write_complete;
logic m_read_complete;
logic m_write_pending;
logic m_flush_pending;
logic m_read_pending;
logic m_read_req;
logic m_write_req;
logic m_flush_req;
logic [FLUSH_TIMER_LEN-1:0] m_flush_req_d;
logic [MEM_BURST_WIDTH:0] m_words_to_write;

cdc_pulse write_req_cdc(
    .rstn(rstn_i),
    .clk_src(vin_clk_i),
    .clk_dest(mem_clk_i),
    .pulse_src(vin_buf_data_ready_i),
    .pulse_dest(m_write_req)
);

cdc_pulse write_flush_cdc(
    .rstn(rstn_i),
    .clk_src(vin_clk_i),
    .clk_dest(mem_clk_i),
    .pulse_src(vin_buf_data_flush_i),
    .pulse_dest(m_flush_req)
);

cdc_pulse read_req_cdc(
    .rstn(rstn_i),
    .clk_src(vout_clk_i),
    .clk_dest(mem_clk_i),
    .pulse_src(vout_buf_data_req_i),
    .pulse_dest(m_read_req)
);

cdc_pulse read_complete_cdc(
    .rstn(rstn_i),
    .clk_src(mem_clk_i),
    .clk_dest(vout_clk_i),
    .pulse_src(m_read_complete),
    .pulse_dest(vout_buf_rd_complete_o)
);

assign mem_rd_en_o = (mem_state == READ) && (m_read_req_count < MEM_BURST_SIZE);
assign mem_wr_en_o = (mem_state == WRITE) && (m_write_req_count < MEM_BURST_SIZE);
assign m_fifo_pop = mem_wr_en_o && (!mem_busy_i);

always_ff @(posedge mem_clk_i or negedge rstn_i) begin
    if(!rstn_i) begin
        mem_state <= IDLE;
        m_write_complete <= 0;
        m_read_complete <= 0;
        m_read_req_count <= 0;
        m_write_req_count <= 0;
        m_read_pending <= 0;
        m_write_pending <= 0;
        m_flush_pending <= 0;
        mem_addr_o <= 0;
        m_flush_req_d <= 0;
        m_words_to_write <= 0;
    end else begin
        // Enforce a few cycles of delay after the flush request
        // This ensures that the last FIFO push from the video input
        // side will be present in the memory clock domain, and the 
        // read count will be updated correctly.
        m_flush_req_d <= {m_flush_req_d[(FLUSH_TIMER_LEN-2):0], m_flush_req};

        m_write_complete <= 0;
        m_read_complete <= 0;

        if (mem_state != IDLE) begin
            if (m_read_req) begin
                m_read_pending <= 1;
            end
            if (m_write_req) begin
                m_write_pending <= 1;
            end
            if (m_flush_req_d[FLUSH_TIMER_LEN-1]) begin
                m_flush_pending <= 1;
            end
        end

        case(mem_state)
        IDLE: begin
            if(m_read_req || m_read_pending) begin
                mem_state <= READ;
                m_read_pending <= 0;
                mem_addr_o <= o_rd_addr; 
                m_read_req_count <= 0;
                if(m_write_req) begin // simultaneous requests, pend the write
                    m_write_pending <= 1;
                end
            end else if(m_write_req || m_write_pending) begin
                mem_state <= WRITE;
                m_write_pending <= 0;
                mem_addr_o <= i_wr_addr;
                m_write_req_count <= 0;
                m_words_to_write <= MEM_BURST_SIZE;
            end else if(m_flush_req_d[FLUSH_TIMER_LEN-1] || m_flush_pending) begin
                // same as write, but only push the amount currently in 
                // the fifo. might not be a full burst number of words
                mem_state <= WRITE;
                m_flush_pending <= 0;
                mem_addr_o <= i_wr_addr;
                m_write_req_count <= 0;
                m_words_to_write <= m_input_fifo_count;
            end
        end
        READ: begin
            if(m_read_req_count < MEM_BURST_SIZE) begin
                if(!mem_busy_i) begin
                    m_read_req_count <= m_read_req_count + 1;
                    mem_addr_o <= mem_addr_o + MEM_INCREMENT;
                end
            end else begin
                m_read_complete <= 1;
                mem_state <= IDLE;  // Don't need to wait for data to be received, can immediately process next command.
                                    // FIFO will take in data as it comes
            end
        end
        WRITE: begin
            if(m_write_req_count < m_words_to_write) begin
                if(!mem_busy_i) begin
                    m_write_req_count <= m_write_req_count + 1;
                    mem_addr_o <= mem_addr_o + MEM_INCREMENT;
                end
            end else begin
                mem_state <= IDLE;
                m_write_complete <= 1;
            end
            
        end
        default: begin
            mem_state <= IDLE;
        end
        endcase
    end
end

function logic[$clog2(MAX_LINE_WIDTH):0] calc_line_width (input logic [9:0] line_len);
    integer clw_i;
    for (clw_i = 1; clw_i < MAX_LINE_WIDTH+1; clw_i = clw_i + 1) begin
        if(line_len < (1 << clw_i))
            return clw_i;
    end
    return 0;
endfunction

endmodule

module cdc_pulse
(
    input  logic rstn,
    input  logic clk_src,
    input  logic clk_dest,
    input  logic pulse_src,
    output logic pulse_dest
);

logic       src_toggle;
logic [2:0] dest_toggle;


always_ff @(posedge clk_src or negedge rstn) begin
    if(!rstn) begin
        src_toggle <= 0;
    end else begin
        if(pulse_src) 
            src_toggle <= ~src_toggle;
    end
end

always_ff @(posedge clk_dest or negedge rstn) begin
    if(!rstn) begin
        dest_toggle <= 3'b000;
    end else begin
        dest_toggle <= {dest_toggle[1:0], src_toggle};
    end
end

assign pulse_dest = dest_toggle[2] ^ dest_toggle[1];

endmodule
